baseURL = "https://jackcary.com/"
languageCode = "en-us"
title = "Jack Cary"
enableRobotsTXT = true
googleAnalytics = "UA-105680531-1"
metaDataFormat = "toml"

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  title = "Contact"
  url = "/contact/"
  weight = 100
