baseURL = "https://jackcary.com/"
languageCode = "en-us"

title = "Jack Cary"

enableRobotsTXT = true
googleAnalytics = "UA-105680531-1"
metaDataFormat = "toml"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.speakerDeck]
    disable = false
  [privacy.twitter]
    disable = false
    enableDNT = true
  [privacy.vimeo]
    disable = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[params]
  subtitle = "Software Consultant"
  location = "Burlington, Vermont"

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/about/"
  weight = 100

[[menu.main]]
  identifier = "services"
  name = "Services"
  title = "Services"
  url = "/services/"
  weight = 200

[[menu.main]]
  identifier = "experience"
  name = "Experience"
  title = "Experience"
  url = "/experience/"
  weight = 300

[[menu.main]]
  identifier = "skills"
  name = "Skills"
  title = "Skills"
  url = "/skills/"
  weight = 400

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  title = "Contact"
  url = "/contact/"
  weight = 500
